(() => {
  "use strict";

  const K_KEY="keiba_ev_tracker_records_v1", K_SETTINGS_KEY="keiba_ev_tracker_settings_v1", S_KEY="pocket_money_stock_records_v1", APP_KEY="pocket_money_app_v1";
  const $=id=>document.getElementById(id);
  const load=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
  let keiba=load(K_KEY,[]),stocks=load(S_KEY,[]),kSettings=load(K_SETTINGS_KEY,{monthlyBudget:10000,modelVersion:"v4-AB"}),app=load(APP_KEY,{activeTab:"keiba"});
  const save=()=>{localStorage.setItem(K_KEY,JSON.stringify(keiba));localStorage.setItem(S_KEY,JSON.stringify(stocks));localStorage.setItem(K_SETTINGS_KEY,JSON.stringify(kSettings));localStorage.setItem(APP_KEY,JSON.stringify(app));};
  const n=v=>v===""||v==null?null:(Number.isFinite(Number(v))?Number(v):null), yen=v=>`${Math.round(Number(v||0)).toLocaleString("ja-JP")}円`, pct=(v,d=1)=>v==null||!Number.isFinite(Number(v))?"—":`${Number(v).toFixed(d)}%`;
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const uuid=()=>crypto.randomUUID?crypto.randomUUID():`id_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
  const csvEsc=v=>`"${String(v??"").replace(/"/g,'""')}"`;
  function download(name,content,type){const b=new Blob([content],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
  const vType=r=>r.validationType==="B"||r.retrospective===true?"B":"A";
  const vLabel=r=>vType(r)==="B"?"B 後付け":"A 事前";

  function injectABUI(){
    const style=document.createElement("style");style.textContent=`.ab-box{margin:14px 0;padding:14px;border:1px solid #d1d5db;border-radius:12px;background:#fff}.ab-title{font-weight:800;margin-bottom:8px}.ab-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ab-mini{padding:10px;border-radius:10px;background:#f9fafb}.ab-mini strong{display:block;font-size:1.15rem;margin-top:4px}.ab-note{font-size:.84rem;color:#6b7280;margin-top:8px}.ab-tag{display:inline-block;padding:2px 7px;border-radius:999px;font-size:.78rem;font-weight:800;background:#eef2ff}.ab-tag.b{background:#fff7ed}@media(max-width:640px){.ab-grid{grid-template-columns:1fr}}`;
    document.head.appendChild(style);
    const kp=$("keibaPanel"),sp=$("stockPanel");
    const kbox=document.createElement("section");kbox.className="ab-box";kbox.innerHTML=`<div class="ab-title">A/B 検証</div><div class="ab-grid"><div class="ab-mini">A：事前予想<strong id="kAbA">—</strong></div><div class="ab-mini">A+B：参考<strong id="kAbAll">—</strong></div></div><div class="ab-note">本番評価はAのみ。Bは結果判明後の後付け検証で、サンプル拡張用です。</div>`;kp.insertBefore(kbox,kp.children[1]||null);
    const sbox=document.createElement("section");sbox.className="ab-box";sbox.innerHTML=`<div class="ab-title">A/B 検証</div><div class="ab-grid"><div class="ab-mini">A：事前エントリー<strong id="sAbA">—</strong></div><div class="ab-mini">A+B：参考<strong id="sAbAll">—</strong></div></div><div class="ab-note">本番評価はAのみ。Bは後付け検証として別集計します。</div>`;sp.insertBefore(sbox,sp.children[1]||null);
    const kf=$("kFilterResult")?.parentElement;if(kf&&!$("kFilterValidation")){const sel=document.createElement("select");sel.id="kFilterValidation";sel.innerHTML='<option value="">区分：すべて</option><option value="A">A：事前</option><option value="B">B：後付け</option>';kf.appendChild(sel)}
    const sf=$("sFilterResult")?.parentElement;if(sf&&!$("sFilterValidation")){const sel=document.createElement("select");sel.id="sFilterValidation";sel.innerHTML='<option value="">区分：すべて</option><option value="A">A：事前</option><option value="B">B：後付け</option>';sf.appendChild(sel)}
    const eyebrow=document.querySelector(".eyebrow");if(eyebrow)eyebrow.textContent="POCKET MONEY TRACKER v4.0 A/B";
    const saveText=document.querySelector(".howto p");if(saveText)saveText.textContent="読み込んだ記録はこのブラウザにも保存されます。A=事前予想、B=後付け検証として分離集計します。";
  }

  function setTab(tab){app.activeTab=tab;save();document.querySelectorAll(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));$("keibaPanel").classList.toggle("active",tab==="keiba");$("stockPanel").classList.toggle("active",tab==="stock")}
  document.querySelectorAll(".tab-btn").forEach(b=>b.addEventListener("click",()=>setTab(b.dataset.tab)));

  function kStableId(r){if(r.id)return String(r.id);const raw=[r.raceDate,r.track,r.raceNo,r.betType,r.selection].map(x=>String(x??"").trim()).join("|");let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619)}return `keiba_${(h>>>0).toString(16)}`}
  function kNormalize(src){const r={...src};r.id=kStableId(r);r.assetType="keiba";r.validationType=vType(r);r.retrospective=r.validationType==="B";r.raceDate=r.raceDate||r.date||"";r.track=r.track||"";r.raceNo=n(r.raceNo);r.betType=r.betType||"";r.selection=r.selection||"";r.predProb=n(r.predProb??r.hitProbability);r.evalOdds=n(r.evalOdds??r.odds??r.oddsLow);r.oddsLow=n(r.oddsLow??r.evalOdds??r.odds);r.oddsHigh=n(r.oddsHigh);r.stake=n(r.stake??r.virtualStake)??100;r.popularity=n(r.popularity);r.resultStatus=r.resultStatus||"未確定";r.payoutPer100=n(r.payoutPer100);r.analysisMemo=r.analysisMemo||r.memo||r.reason||"";r.startTime=r.startTime||"";r.finalOddsLow=n(r.finalOddsLow);r.finalOddsHigh=n(r.finalOddsHigh);r.decision=r.decision||"購入";r.createdAt=r.createdAt||new Date().toISOString();r.updatedAt=new Date().toISOString();return r}
  const kEv=r=>r.predProb!=null&&r.evalOdds!=null?Number(r.predProb)*Number(r.evalOdds):null;
  const kReturn=r=>!r.resultStatus||r.resultStatus==="未確定"?null:(Number(r.stake)||0)/100*(Number(r.payoutPer100)||0);
  function kEvBand(ev){if(ev==null)return"—";if(ev<100)return"<100%";if(ev>=130)return"130%+";const lo=Math.floor(ev/5)*5;return`${lo}-${(lo+4.9).toFixed(1)}%`}
  function upsertKeiba(list){let add=0,upd=0;for(const raw of list){const r=kNormalize(raw),i=keiba.findIndex(x=>x.id===r.id);if(i>=0){keiba[i]={...keiba[i],...r,createdAt:keiba[i].createdAt||r.createdAt};upd++}else{keiba.push(r);add++}}save();return{add,upd}}
  function kMetrics(arr){const bought=arr.filter(r=>r.decision!=="見送り"),settled=bought.filter(r=>r.resultStatus&&r.resultStatus!=="未確定"),stake=settled.reduce((s,r)=>s+(Number(r.stake)||0),0),ret=settled.reduce((s,r)=>s+(kReturn(r)||0),0);return{bought,settled,stake,ret,profit:ret-stake,roi:stake?ret/stake*100:null,hit:settled.length?settled.filter(r=>r.resultStatus==="的中").length/settled.length*100:null}}
  function renderKeibaSummary(){const a=keiba.filter(r=>vType(r)==="A"),m=kMetrics(a),all=kMetrics(keiba);$("kStatBought").textContent=m.bought.length;$("kStatStake").textContent=yen(m.bought.reduce((s,r)=>s+(Number(r.stake)||0),0));$("kStatReturn").textContent=yen(m.ret);$("kStatProfit").textContent=yen(m.profit);$("kStatProfit").className=m.profit>0?"profit-positive":m.profit<0?"profit-negative":"";$("kStatRoi").textContent=pct(m.roi);$("kStatHitRate").textContent=pct(m.hit);const evs=m.bought.map(kEv).filter(v=>v!=null);$("kStatAvgEv").textContent=evs.length?pct(avg(evs)):"—";$("kStatCandidates").textContent=a.length;$("kAbA").textContent=`${m.settled.length}件 / 回収率 ${pct(m.roi)}`;$("kAbAll").textContent=`${all.settled.length}件 / 回収率 ${pct(all.roi)}`;renderBudget()}
  function renderBudget(){const d=new Date(),ym=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,used=keiba.filter(r=>vType(r)==="A"&&r.decision!=="見送り"&&String(r.raceDate||"").startsWith(ym)).reduce((s,r)=>s+(Number(r.stake)||0),0),b=Number(kSettings.monthlyBudget)||0;$("budgetMonthLabel").textContent=`${d.getFullYear()}年${d.getMonth()+1}月`;$("budgetText").textContent=`${used.toLocaleString("ja-JP")} / ${b.toLocaleString("ja-JP")}円`;$("budgetBarFill").style.width=`${b?Math.min(100,used/b*100):0}%`;$("budgetBarFill").style.background=used>b?"#b91c1c":"#2563eb"}
  function kGroups(keyFn){const m=new Map();keiba.filter(r=>vType(r)==="A").forEach(r=>{const k=keyFn(r)||"—";if(!m.has(k))m.set(k,[]);m.get(k).push(r)});return[...m.entries()]}
  function renderKBreakdown(id,groups){$(id).innerHTML=`<thead><tr><th>区分</th><th>件数</th><th>確定</th><th>的中率</th><th>平均EV</th><th>回収率</th></tr></thead><tbody>${groups.map(([k,a])=>{const b=a.filter(r=>r.decision!=="見送り"),s=b.filter(r=>r.resultStatus&&r.resultStatus!=="未確定"),st=s.reduce((x,r)=>x+(Number(r.stake)||0),0),ret=s.reduce((x,r)=>x+(kReturn(r)||0),0),ev=avg(b.map(kEv).filter(v=>v!=null));return`<tr><td>${esc(k)}</td><td>${a.length}</td><td>${s.length}</td><td>${s.length?pct(s.filter(r=>r.resultStatus==="的中").length/s.length*100):"—"}</td><td>${ev==null?"—":pct(ev)}</td><td>${st?pct(ret/st*100):"—"}</td></tr>`}).join("")}</tbody>`}
  function renderKCalibration(){const base=keiba.filter(r=>vType(r)==="A"),bins=[[0,10],[10,20],[20,30],[30,40],[40,50],[50,60],[60,70],[70,80],[80,90],[90,101]];$("calibrationTable").innerHTML=`<thead><tr><th>予測確率</th><th>件数</th><th>確定</th><th>平均予測</th><th>実的中率</th></tr></thead><tbody>${bins.map(([lo,hi])=>{const a=base.filter(r=>r.predProb!=null&&r.predProb>=lo&&r.predProb<hi),s=a.filter(r=>r.resultStatus&&r.resultStatus!=="未確定");return`<tr><td>${lo}-${hi===101?100:hi}%</td><td>${a.length}</td><td>${s.length}</td><td>${a.length?pct(avg(a.map(r=>Number(r.predProb)))):"—"}</td><td>${s.length?pct(s.filter(r=>r.resultStatus==="的中").length/s.length*100):"—"}</td></tr>`}).join("")}</tbody>`}
  function renderKeibaRecords(){const q=$("kSearchText").value.trim().toLowerCase(),bt=$("kFilterBetType").value,rs=$("kFilterResult").value,vt=$("kFilterValidation")?.value||"";const list=[...keiba].filter(r=>(!q||[r.track,r.selection,r.analysisMemo].join(" ").toLowerCase().includes(q))&&(!bt||r.betType===bt)&&(!rs||r.resultStatus===rs)&&(!vt||vType(r)===vt)).sort((a,b)=>String(b.raceDate).localeCompare(String(a.raceDate))||Number(b.raceNo||0)-Number(a.raceNo||0));$("keibaRecordsTable").innerHTML=`<thead><tr><th>区分</th><th>日付</th><th>場/R</th><th>券種</th><th>買い目</th><th>的中率</th><th>判断オッズ</th><th>EV</th><th>EV帯</th><th>仮想額</th><th>結果</th><th>損益</th><th>操作</th></tr></thead><tbody>${list.map(r=>{const ev=kEv(r),ret=kReturn(r),profit=ret==null?null:ret-(Number(r.stake)||0),badge=r.resultStatus==="的中"?"badge-hit":r.resultStatus==="不的中"?"badge-miss":"badge-pending";return`<tr><td><span class="ab-tag ${vType(r)==="B"?"b":""}">${vLabel(r)}</span></td><td>${esc(r.raceDate)}</td><td>${esc(r.track)} ${r.raceNo||""}R</td><td>${esc(r.betType)}</td><td>${esc(r.selection)}</td><td>${pct(r.predProb)}</td><td>${r.evalOdds??"—"}</td><td>${ev==null?"—":pct(ev)}</td><td>${kEvBand(ev)}</td><td>${yen(r.stake)}</td><td><span class="badge ${badge}">${esc(r.resultStatus||"未確定")}</span></td><td class="${profit>0?"profit-positive":profit<0?"profit-negative":""}">${profit==null?"—":yen(profit)}</td><td><div class="row-actions"><button class="mini-btn" data-k-edit="${esc(r.id)}">編集</button><button class="mini-btn delete" data-k-del="${esc(r.id)}">削除</button></div></td></tr>`}).join("")}</tbody>`;$("keibaEmpty").style.display=list.length?"none":"block";const types=[...new Set(keiba.map(r=>r.betType).filter(Boolean))].sort(),cur=$("kFilterBetType").value;$("kFilterBetType").innerHTML=`<option value="">券種：すべて</option>`+types.map(x=>`<option>${esc(x)}</option>`).join("");$("kFilterBetType").value=cur}
  function renderKeibaAll(){renderKeibaSummary();renderKBreakdown("byBetTypeTable",kGroups(r=>r.betType));renderKBreakdown("byEvBandTable",kGroups(r=>kEvBand(kEv(r))).sort((a,b)=>String(a[0]).localeCompare(String(b[0]),"ja")));renderKCalibration();renderKeibaRecords()}
  function updateKPreview(){const p=n($("kPredProb").value),o=n($("kEvalOdds").value),ev=p!=null&&o!=null?p*o:null,min=p>0?100/p:null;$("kFairOddsPreview").textContent=min?`${min.toFixed(2)}倍`:"—";$("kEvPreview").textContent=ev!=null?pct(ev):"—";$("kEvPreview").className=ev>=100?"profit-positive":ev!=null?"profit-negative":"";$("kMinOddsPreview").textContent=min?`${min.toFixed(2)}倍`:"—"}
  function kReset(){const d=new Date().toISOString().slice(0,10);$("keibaForm").reset();$("kId").value="";$("kRaceDate").value=d;$("kStake").value="100";$("kResultStatus").value="未確定";$("kFormError").textContent="";updateKPreview()}
  function kEdit(id){const r=keiba.find(x=>x.id===id);if(!r)return;$("keibaManualDetails").open=true;$("kId").value=r.id;$("kRaceDate").value=r.raceDate||"";$("kTrack").value=r.track||"";$("kRaceNo").value=r.raceNo??"";$("kStartTime").value=r.startTime||"";$("kBetType").value=r.betType||"単勝";$("kSelection").value=r.selection||"";$("kPredProb").value=r.predProb??"";$("kEvalOdds").value=r.evalOdds??"";$("kStake").value=r.stake??100;$("kPopularity").value=r.popularity??"";$("kResultStatus").value=r.resultStatus||"未確定";$("kPayoutPer100").value=r.payoutPer100??"";$("kMemo").value=r.analysisMemo||"";updateKPreview();$("keibaManualDetails").scrollIntoView({behavior:"smooth"})}

  function sStableId(r){if(r.id)return String(r.id);const raw=[r.code||r.ticker,r.entryDate||r.analysisDate||r.analyzedAt].map(x=>String(x??"").trim()).join("|");let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619)}return`stock_${(h>>>0).toString(16)}`}
  function sNormalize(src){const r={...src};r.id=sStableId(r);r.assetType="stock";r.validationType=vType(r);r.retrospective=r.validationType==="B";r.name=r.name||r.stockName||r.company||"";r.code=String(r.code||r.ticker||"");r.entryDate=r.entryDate||r.date||"";r.status=r.status||r.positionStatus||"監視";r.entryPrice=n(r.entryPrice??r.buyPrice);r.virtualAmount=n(r.virtualAmount??r.amount)??10000;r.targetPrice=n(r.targetPrice??r.target);r.stopLoss=n(r.stopLoss??r.stop);r.holdDays=n(r.holdDays);r.analyzedAt=r.analyzedAt||r.analysisTime||"";r.thesis=r.thesis||r.reason||r.analysisMemo||"";r.exitDate=r.exitDate||"";r.exitPrice=n(r.exitPrice??r.sellPrice);r.exitReason=r.exitReason||"";r.currentPrice=n(r.currentPrice);r.exitMemo=r.exitMemo||"";r.createdAt=r.createdAt||new Date().toISOString();r.updatedAt=new Date().toISOString();if(r.exitPrice!=null)r.status="決済済";return r}
  function upsertStocks(list){let add=0,upd=0;for(const raw of list){const r=sNormalize(raw),i=stocks.findIndex(x=>x.id===r.id);if(i>=0){stocks[i]={...stocks[i],...r,createdAt:stocks[i].createdAt||r.createdAt};upd++}else{stocks.push(r);add++}}save();return{add,upd}}
  function sCalc(r){if(r.entryPrice==null||r.exitPrice==null||r.entryPrice===0)return{rate:null,profit:null};const rate=(r.exitPrice-r.entryPrice)/r.entryPrice*100,profit=(Number(r.virtualAmount)||0)*rate/100;return{rate,profit}}
  function sRR(r){if(r.entryPrice==null||r.targetPrice==null||r.stopLoss==null)return null;const up=r.targetPrice-r.entryPrice,down=r.entryPrice-r.stopLoss;return down>0?up/down:null}
  function sMetrics(arr){const closed=arr.filter(r=>r.status==="決済済"&&r.exitPrice!=null),vals=closed.map(sCalc),wins=vals.filter(x=>x.profit>0),loss=vals.filter(x=>x.profit<0),profit=vals.reduce((s,x)=>s+(x.profit||0),0);return{closed,vals,wins,loss,profit,winRate:closed.length?wins.length/closed.length*100:null,avgRet:vals.length?avg(vals.map(x=>x.rate).filter(x=>x!=null)):null}}
  function renderStocksSummary(){const a=stocks.filter(r=>vType(r)==="A"),m=sMetrics(a),all=sMetrics(stocks),open=a.filter(r=>r.status==="保有中");$("sStatOpen").textContent=open.length;$("sStatClosed").textContent=m.closed.length;$("sStatWinRate").textContent=pct(m.winRate);$("sStatProfit").textContent=yen(m.profit);$("sStatProfit").className=m.profit>0?"profit-positive":m.profit<0?"profit-negative":"";$("sStatAvgReturn").textContent=pct(m.avgRet);$("sStatAvgWin").textContent=m.wins.length?yen(avg(m.wins.map(x=>x.profit))):"—";$("sStatAvgLoss").textContent=m.loss.length?yen(avg(m.loss.map(x=>x.profit))):"—";$("sStatTotal").textContent=a.length;$("sAbA").textContent=`${m.closed.length}件 / 損益 ${yen(m.profit)}`;$("sAbAll").textContent=`${all.closed.length}件 / 損益 ${yen(all.profit)}`}
  function renderStockBreakdowns(){const base=stocks.filter(r=>vType(r)==="A"),group=(fn)=>{const m=new Map();base.forEach(r=>{const k=fn(r)||"—";if(!m.has(k))m.set(k,[]);m.get(k).push(r)});return[...m.entries()]};const table=(id,groups)=>{$(id).innerHTML=`<thead><tr><th>区分</th><th>件数</th><th>決済</th><th>勝率</th><th>損益</th></tr></thead><tbody>${groups.map(([k,a])=>{const m=sMetrics(a);return`<tr><td>${esc(k)}</td><td>${a.length}</td><td>${m.closed.length}</td><td>${pct(m.winRate)}</td><td>${yen(m.profit)}</td></tr>`}).join("")}</tbody>`};table("stockStatusTable",group(r=>r.status));table("stockExitReasonTable",group(r=>r.exitReason||"未決済"))}
  function renderStockRecords(){const q=$("sSearchText").value.trim().toLowerCase(),st=$("sFilterStatus").value,res=$("sFilterResult").value,vt=$("sFilterValidation")?.value||"";const list=[...stocks].filter(r=>{const c=sCalc(r);return(!q||[r.name,r.code,r.thesis].join(" ").toLowerCase().includes(q))&&(!st||r.status===st)&&(!vt||vType(r)===vt)&&(!res||(res==="win"&&c.profit>0)||(res==="loss"&&c.profit<0))}).sort((a,b)=>String(b.entryDate).localeCompare(String(a.entryDate)));$("stockRecordsTable").innerHTML=`<thead><tr><th>区分</th><th>日付</th><th>銘柄</th><th>状態</th><th>買値</th><th>現在/決済</th><th>目標</th><th>損切</th><th>RR</th><th>損益</th><th>操作</th></tr></thead><tbody>${list.map(r=>{const c=sCalc(r),px=r.exitPrice??r.currentPrice;return`<tr><td><span class="ab-tag ${vType(r)==="B"?"b":""}">${vLabel(r)}</span></td><td>${esc(r.entryDate)}</td><td>${esc(r.name)}<br><small>${esc(r.code)}</small></td><td>${esc(r.status)}</td><td>${r.entryPrice??"—"}</td><td>${px??"—"}</td><td>${r.targetPrice??"—"}</td><td>${r.stopLoss??"—"}</td><td>${sRR(r)==null?"—":sRR(r).toFixed(2)}</td><td class="${c.profit>0?"profit-positive":c.profit<0?"profit-negative":""}">${c.profit==null?"—":`${yen(c.profit)} (${pct(c.rate)})`}</td><td><div class="row-actions"><button class="mini-btn" data-s-edit="${esc(r.id)}">編集</button><button class="mini-btn delete" data-s-del="${esc(r.id)}">削除</button></div></td></tr>`}).join("")}</tbody>`;$("stockEmpty").style.display=list.length?"none":"block"}
  function renderStocksAll(){renderStocksSummary();renderStockBreakdowns();renderStockRecords()}
  function updateSPreview(){const e=n($("sEntryPrice").value),t=n($("sTarget").value),sl=n($("sStop").value),up=e&&t?(t-e)/e*100:null,down=e&&sl?(e-sl)/e*100:null,rr=down>0?up/down:null;$("sUpsidePreview").textContent=pct(up);$("sDownsidePreview").textContent=pct(down);$("sRrPreview").textContent=rr==null?"—":rr.toFixed(2)}
  function sReset(){const d=new Date().toISOString().slice(0,10);$("stockForm").reset();$("sId").value="";$("sEntryDate").value=d;$("sAmount").value="10000";$("sStatus").value="監視";$("sFormError").textContent="";updateSPreview()}
  function sEdit(id){const r=stocks.find(x=>x.id===id);if(!r)return;$("stockManualDetails").open=true;$("sId").value=r.id;$("sName").value=r.name||"";$("sCode").value=r.code||"";$("sEntryDate").value=r.entryDate||"";$("sStatus").value=r.status||"監視";$("sEntryPrice").value=r.entryPrice??"";$("sAmount").value=r.virtualAmount??10000;$("sTarget").value=r.targetPrice??"";$("sStop").value=r.stopLoss??"";$("sHoldDays").value=r.holdDays??"";$("sAnalyzedAt").value=r.analyzedAt||"";$("sThesis").value=r.thesis||"";$("sExitDate").value=r.exitDate||"";$("sExitPrice").value=r.exitPrice??"";$("sExitReason").value=r.exitReason||"";$("sCurrentPrice").value=r.currentPrice??"";$("sExitMemo").value=r.exitMemo||"";updateSPreview();$("stockManualDetails").scrollIntoView({behavior:"smooth"})}

  function classifyImport(data){if(Array.isArray(data)){return{keiba:data.filter(x=>x.assetType==="keiba"||x.raceDate||x.track),stocks:data.filter(x=>x.assetType==="stock"||x.code||x.ticker)}}return{keiba:data.keibaRecords||data.keiba||[],stocks:data.stockRecords||data.stocks||[]}}
  function importFile(file,restore=false){const fr=new FileReader();fr.onload=()=>{try{const data=JSON.parse(fr.result),c=classifyImport(data);if(restore&&data.settings)kSettings={...kSettings,...data.settings};const k=upsertKeiba(c.keiba),s=upsertStocks(c.stocks);$("importStatus").textContent=`読み込み完了：競馬 ${k.add}件追加/${k.upd}件更新、株 ${s.add}件追加/${s.upd}件更新`;$("importStatus").className="status-line status-ok";renderAll()}catch(e){$("importStatus").textContent=`読み込み失敗：${e.message||"JSONを確認してください"}`;$("importStatus").className="status-line status-bad"}};fr.readAsText(file)}
  function exportAllJson(){download(`pocket_money_backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({app:"Pocket Money",version:4,classification:{A:"事前予想・本番評価",B:"後付け検証・参考"},exportedAt:new Date().toISOString(),settings:kSettings,keibaRecords:keiba,stockRecords:stocks},null,2),"application/json;charset=utf-8")}
  function exportKeibaCsv(){const fields=[["id","ID"],["validationType","A/B"],["raceDate","日付"],["track","競馬場"],["raceNo","R"],["startTime","発走"],["betType","券種"],["selection","買い目"],["predProb","推定的中率%"],["evalOdds","判断オッズ"],["stake","仮想購入額"],["popularity","人気"],["analysisMemo","分析メモ"],["resultStatus","結果"],["payoutPer100","払戻100円あたり"]],head=fields.map(x=>csvEsc(x[1])).join(","),lines=keiba.map(r=>fields.map(([k])=>csvEsc(r[k])).join(","));download(`keiba_records_${new Date().toISOString().slice(0,10)}.csv`,"\ufeff"+[head,...lines].join("\r\n"),"text/csv;charset=utf-8")}
  function exportStockCsv(){const fields=[["id","ID"],["validationType","A/B"],["entryDate","エントリー日"],["name","銘柄名"],["code","コード"],["status","状態"],["entryPrice","仮想買値"],["virtualAmount","仮想投資額"],["targetPrice","目標株価"],["stopLoss","損切り水準"],["thesis","根拠"],["exitDate","決済日"],["exitPrice","決済値"],["exitReason","決済理由"]],head=fields.map(x=>csvEsc(x[1])).join(","),lines=stocks.map(r=>fields.map(([k])=>csvEsc(r[k])).join(","));download(`stock_records_${new Date().toISOString().slice(0,10)}.csv`,"\ufeff"+[head,...lines].join("\r\n"),"text/csv;charset=utf-8")}

  injectABUI();
  $("monthlyBudget").value=kSettings.monthlyBudget??10000;$("modelVersion").value=kSettings.modelVersion||"v4-AB";
  ["monthlyBudget","modelVersion"].forEach(id=>$(id).addEventListener("change",()=>{kSettings.monthlyBudget=n($("monthlyBudget").value)??0;kSettings.modelVersion=$("modelVersion").value.trim()||"v4-AB";save();renderKeibaAll()}));
  ["kPredProb","kEvalOdds"].forEach(id=>$(id).addEventListener("input",updateKPreview));["sEntryPrice","sTarget","sStop"].forEach(id=>$(id).addEventListener("input",updateSPreview));
  ["kSearchText","kFilterBetType","kFilterResult","kFilterValidation"].forEach(id=>$(id)?.addEventListener(id==="kSearchText"?"input":"change",renderKeibaRecords));["sSearchText","sFilterStatus","sFilterResult","sFilterValidation"].forEach(id=>$(id)?.addEventListener(id==="sSearchText"?"input":"change",renderStockRecords));
  $("runSimulationBtn").addEventListener("click",()=>{const th=n($("simEvThreshold").value)??110,a=keiba.filter(r=>vType(r)==="A"&&kEv(r)!=null&&kEv(r)>=th&&r.resultStatus&&r.resultStatus!=="未確定"),stake=a.length*100,ret=a.reduce((s,r)=>s+(Number(r.payoutPer100)||0),0),profit=ret-stake;$("simulationResult").innerHTML=a.length?`A事前のみ：対象 <strong>${a.length}件</strong> / 仮想投資 ${yen(stake)} / 仮想払戻 ${yen(ret)} / 損益 <strong class="${profit>=0?"profit-positive":"profit-negative"}">${yen(profit)}</strong> / 回収率 ${pct(stake?ret/stake*100:null)}`:"A事前予想の確定済み対象記録がありません。"});
  $("keibaForm").addEventListener("submit",e=>{e.preventDefault();const old=keiba.find(x=>x.id===$("kId").value),r=kNormalize({id:$("kId").value||uuid(),validationType:old?.validationType||"A",raceDate:$("kRaceDate").value,track:$("kTrack").value.trim(),raceNo:n($("kRaceNo").value),startTime:$("kStartTime").value,betType:$("kBetType").value,selection:$("kSelection").value.trim(),predProb:n($("kPredProb").value),evalOdds:n($("kEvalOdds").value),stake:n($("kStake").value)??100,popularity:n($("kPopularity").value),resultStatus:$("kResultStatus").value,payoutPer100:n($("kPayoutPer100").value),analysisMemo:$("kMemo").value.trim(),decision:"購入"}),errs=[];if(!r.raceDate)errs.push("日付");if(!r.track)errs.push("競馬場");if(!r.raceNo)errs.push("R");if(!r.selection)errs.push("買い目");if(r.predProb==null)errs.push("推定的中率");if(r.evalOdds==null)errs.push("判断オッズ");if(errs.length){$("kFormError").textContent=`未入力：${errs.join("、")}`;return}upsertKeiba([r]);kReset();renderKeibaAll()});
  $("stockForm").addEventListener("submit",e=>{e.preventDefault();const old=stocks.find(x=>x.id===$("sId").value),r=sNormalize({id:$("sId").value||uuid(),validationType:old?.validationType||"A",name:$("sName").value.trim(),code:$("sCode").value.trim(),entryDate:$("sEntryDate").value,status:$("sStatus").value,entryPrice:n($("sEntryPrice").value),virtualAmount:n($("sAmount").value)??10000,targetPrice:n($("sTarget").value),stopLoss:n($("sStop").value),holdDays:n($("sHoldDays").value),analyzedAt:$("sAnalyzedAt").value,thesis:$("sThesis").value.trim(),exitDate:$("sExitDate").value,exitPrice:n($("sExitPrice").value),exitReason:$("sExitReason").value,currentPrice:n($("sCurrentPrice").value),exitMemo:$("sExitMemo").value.trim()}),errs=[];if(!r.name)errs.push("銘柄名");if(!r.code)errs.push("コード");if(!r.entryDate)errs.push("エントリー日");if(errs.length){$("sFormError").textContent=`未入力：${errs.join("、")}`;return}upsertStocks([r]);sReset();renderStocksAll()});
  $("kClearBtn").addEventListener("click",kReset);$("sClearBtn").addEventListener("click",sReset);
  $("keibaRecordsTable").addEventListener("click",e=>{const ed=e.target.closest("[data-k-edit]"),del=e.target.closest("[data-k-del]");if(ed)kEdit(ed.dataset.kEdit);if(del&&confirm("この競馬記録を削除しますか？")){keiba=keiba.filter(r=>r.id!==del.dataset.kDel);save();renderKeibaAll()}});
  $("stockRecordsTable").addEventListener("click",e=>{const ed=e.target.closest("[data-s-edit]"),del=e.target.closest("[data-s-del]");if(ed)sEdit(ed.dataset.sEdit);if(del&&confirm("この株記録を削除しますか？")){stocks=stocks.filter(r=>r.id!==del.dataset.sDel);save();renderStocksAll()}});
  $("chappyImportInput").addEventListener("change",e=>{const f=e.target.files?.[0];if(f)importFile(f);e.target.value=""});$("restoreJsonInput").addEventListener("change",e=>{const f=e.target.files?.[0];if(f)importFile(f,true);e.target.value=""});
  $("exportAllJsonBtn").addEventListener("click",exportAllJson);$("exportKeibaCsvBtn").addEventListener("click",exportKeibaCsv);$("exportStockCsvBtn").addEventListener("click",exportStockCsv);$("deleteAllBtn").addEventListener("click",()=>{if(confirm("競馬と株の全記録を削除します。よろしいですか？")){keiba=[];stocks=[];save();renderAll()}});
  function renderAll(){renderKeibaAll();renderStocksAll()}
  keiba=keiba.map(kNormalize);stocks=stocks.map(sNormalize);save();kReset();sReset();setTab(app.activeTab||"keiba");renderAll();
})();